### ISSUE TITLE
bug report & 优化建议

### ISSUE THREAD

**Issue by kuitos** [ShuyunXIANFESchool/angular-switch#1]
bug:
1. 在外部触发ngModel变化并不能触发绑定的ngChange，如
   
   ``` js
   <button ng-click="state = !state" type="button">button</button>
   <ui-switch ng-model="state" ng-change="change()"></ui-switch>
   ```

优化建议：
1. 既然已经声明 bindToController，则可在 controller 中通过 this.ngModelCtrl 的方式拿到 ngModel controller，不需要单独定义 link 函数。
2. 分离 dom，应该在 switch 组件根节点 添加 ng-click 声明而不是在代码中手动 注册 click 绑定，确保controller 逻辑纯粹(并不是指令中就可以随意操作dom)，组件由状态数据驱动。又比如：
   
   ``` js
   var isActive = element.hasClass('check');
   ```
3. 既然已经在模板中声明
   
   ``` js
   ng-class="{'check': vm.ngModel === (vm.trueValue || true)}"
   ```
   
   指令中实现 `ngModelCtrl.$render` 接口意义在哪？

pr 我就不提了不想写 code hhh

**Comment by hjzheng** [comment]
删除了一些无用的代码，fix这个bug前，先问个问题，声明了 bindToController， 但是在controller中没有拿到 this.ngModelCtrl ?

**Comment by kuitos** [comment]
对 require controller 的初始化绑定 angular 实现有 bug，我正在提 pr，你现在可以通过 $onInit 钩子做逻辑初始化

**Comment by hjzheng** [comment]
@kuitos 👍

**Comment by kuitos** [comment]
@hjzheng 不对 你为什么要在 constructor 里拿 ngModelCtrl ？

**Comment by hjzheng** [comment]
@kuitos 有时间review一下
